version: "3.9"

services:
  api:
    build: .
    # command: uvicorn api:app --host 0.0.0.0 --port ${PORT}
    ports:
      - "${PORT}:8000"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
